### ISSUE TITLE
get error " Fatal signal 6 (SIGABRT), code -6 in tid 8937 (as.tflite), pid 8937 (as.tflite)"

### ISSUE THREAD

**Issue by zhanfeng06** [parai/dms#1]
I download the code, compile a apk, install on android8.1. It complain error "can not find as.tflite" When I open the apk.

Is there as.tflite in the code?

**Comment by parai** [comment]
Hi:
I am not good at android apk programing, I don't know what's wrong, and in fact, the apk part is not fully implemented, it has just feature that use OpenCV to locate face position and cut the face out and then use facenet to do recongnizeion, but it doesn't works as expected, I think some issue of tflite at that time.
I think you need to work on your own to fix it. And I think as.tflite is https://github.com/parai/dms/tree/master/tflite/app/src/main/java/as/tflite maybe, not sure.

Now I am busy on another open source project https://github.com/lwnn/lwnn.

**Comment by zhanfeng06** [comment]
Ok.  I think as.tflite should be a tensorflow lite model. 
Thanks, I will try to fix it.

**Comment by parai** [comment]
I think it's not.
![image](https://user-images.githubusercontent.com/3183386/69724751-7c180f80-1157-11ea-8665-6aefa0975bc3.png)

**Comment by zhanfeng06** [comment]
谢谢，忽略了还有一个链接，要转换获取tflite，https://github.com/parai/facenet_mtcnn_to_mobile
